use_frameworks!

platform :ios, '10.0'

target 'MFYBImageBrowserFeature_Example' do
  pod 'MFYBImageBrowserFeature', :path => '../'

  target 'MFYBImageBrowserFeature_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
